"""Add usrs

Revision ID: 1853eb5186e7
Revises: c8a8cbbc0fc5
Create Date: 2023-01-23 22:22:38.720750

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1853eb5186e7"
down_revision = "c8a8cbbc0fc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA users")
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.LargeBinary(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="users")
    op.execute("DROP SCHEMA processes")
    # ### end Alembic commands ###
