"""Add processes schema

Revision ID: 4d4800579e1e
Revises: 562894b9762e
Create Date: 2022-10-18 22:04:44.278804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4800579e1e'
down_revision = '562894b9762e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA processes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA processes")
    # ### end Alembic commands ###
