"""Add buying process manager state

Revision ID: 5550392a452c
Revises: c8a8cbbc0fc5
Create Date: 2022-10-25 19:47:02.493596

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5550392a452c"
down_revision = "c8a8cbbc0fc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buying",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("buyer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("price_amount", sa.Numeric(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("payment_timeout_at", sa.DateTime(), nullable=True),
        sa.Column("payment_finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("item_id"),
        schema="processes",
    )
    op.drop_table("placeholder", schema="processes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "placeholder",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('processes.placeholder_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="placeholder_pkey"),
        schema="processes",
    )
    op.drop_table("buying", schema="processes")
    # ### end Alembic commands ###
