"""MESSAGE

Revision ID: 76325c4a6afe
Revises: 1853eb5186e7
Create Date: 2025-09-14 19:26:13.103381

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76325c4a6afe"
down_revision = "1853eb5186e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("item_price_currency", sa.String(length=3), nullable=True),
        sa.Column("item_price_amount", sa.Numeric(), nullable=True),
        sa.Column("total_currency", sa.String(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(), nullable=True),
        sa.Column("line_1", sa.String(), nullable=False),
        sa.Column("line_2", sa.String(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("shipped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
