@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(used_stuff_market, "Used Stuff Market") {
    Component(api, "API")
    Component(catalog, "Catalog")
    Component(items, "Items")
    Component(orders, "Orders")
    Component(likes, "Likes")
    Component(negotiations, "Negotiations")
    Component(payments, "Payments")
    Component(availability, "Availability")

    Component(dbcmp, "DB", "", "Everything uses DB,\nrelations skipped for readability")
}

ComponentDb(db, "Database", "PostgreSQL")

Rel(dbcmp, db, "Uses")
Rel_D(api, items, "calls")
Rel_D(api, likes, "calls")
Rel_D(api, negotiations, "calls")
Rel_D(api, catalog, "calls")
Rel_D(api, orders, "calls")
Rel_D(api, payments, "calls")
Rel_D(items, availability, "calls")
Rel_D(orders, availability, "calls")

Lay_D(availability, dbcmp)
@enduml