version: '3.6'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=used_stuff_market
      - POSTGRES_USER=used_stuff_market
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:5.0.14
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: used_stuff_market
      MONGO_INITDB_ROOT_PASSWORD: used_stuff_market

