version: '3.6'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=used_stuff_market
      - POSTGRES_USER=used_stuff_market
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  prometheus:
    image: prom/prometheus:v2.37.2
    ports:
      - '9090:9090'
