[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.mypy]
disallow_untyped_defs = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "sqlalchemy.*",
    "celery",
]
ignore_missing_imports = true

[tool.poetry]
name = "used_stuff_market"
version = "0.1.0"
description = ""
authors = ["Sebastian Buczynski <nnplaya@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.85.0"}
SQLAlchemy = "^1.4.41"
psycopg2-binary = "^2.9.4"
alembic = "^1.8.1"
blinker = "^1.5"
kombu = "^5.2.4"
celery = {extras = ["redis"], version = "^5.2.7"}
lagom = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
black = "^22.10.0"
isort = "^5.10.1"
mockito = "^1.4.0"
pytest-mockito = "^0.0.4"
mypy = "^0.982"
flake8 = "^5.0.4"
Flake8-pyproject = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
